from databases.interfaces import Record as Record
from dio_blog.database import database as database
from dio_blog.model.post import posts as posts
from dio_blog.schemas.post import PostRequest as PostRequest, PostUpdateRequest as PostUpdateRequest

class PostService:
    async def read_all(self, published: bool, limit: int, skip: int) -> list[Record]: ...
    async def read(self, id: int) -> Record: ...
    async def create(self, post: PostRequest) -> int: ...
    async def update(self, id: int, post: PostUpdateRequest) -> Record: ...
    async def delete(self, id: int) -> None: ...
