import abc
from _typeshed import Incomplete
from abc import ABC, abstractmethod
from collections.abc import Generator

ROOT_PATH: Incomplete

class ContasIterador:
    contas: Incomplete
    def __init__(self, contas) -> None: ...
    def __iter__(self): ...
    def __next__(self): ...

class Cliente:
    def __init__(self, endereco) -> None: ...
    @property
    def endereco(self): ...
    @property
    def contas(self): ...
    def adicionar_conta(self, conta) -> None: ...
    def realizar_transacao(self, transacao, conta) -> None: ...

class PessoaFisica(Cliente):
    def __init__(self, nome, cpf, data_nascimento, endereco) -> None: ...
    @property
    def nome(self): ...
    @property
    def cpf(self): ...

class Conta:
    def __init__(self, numero, cliente) -> None: ...
    @classmethod
    def criar_conta(cls, cliente, numero): ...
    @property
    def saldo(self): ...
    @property
    def numero(self): ...
    @property
    def agencia(self): ...
    @property
    def cliente(self): ...
    @property
    def historico(self): ...
    def sacar(self, valor): ...
    def depositar(self, valor): ...

class ContaCorrente(Conta):
    def __init__(self, numero, cliente, limite: float = 500.0, limite_saques: int = 3) -> None: ...
    @property
    def limite(self): ...
    @property
    def limite_saques(self): ...
    def sacar(self, valor): ...

class Historico:
    def __init__(self) -> None: ...
    def adicionar_transacao(self, transacao) -> None: ...
    def transacoes_do_dia(self): ...
    def gerar_relatorio(self, tipo_transacao=None) -> Generator[Incomplete]: ...

class Transacao(ABC, metaclass=abc.ABCMeta):
    @property
    @abstractmethod
    def valor(self): ...
    @abstractmethod
    def registrar(self, conta): ...

class Deposito(Transacao):
    def __init__(self, valor) -> None: ...
    @property
    def valor(self): ...
    def registrar(self, conta) -> None: ...

class Saque(Transacao):
    def __init__(self, valor) -> None: ...
    @property
    def valor(self): ...
    def registrar(self, conta) -> None: ...

def log_transacao(func): ...
def menu(): ...
def filtrar_cliente(cpf, clientes): ...
def recuperar_conta_cliente(cliente): ...
@log_transacao
def depositar(clientes) -> None: ...
@log_transacao
def sacar(clientes) -> None: ...
@log_transacao
def exibir_extrato(clientes) -> None: ...
@log_transacao
def criar_cliente(clientes) -> None: ...
@log_transacao
def criar_conta(clientes, contas) -> None: ...
def listar_contas(contas) -> None: ...
def main() -> None: ...
