from _typeshed import Incomplete

ROOT_PATH: Incomplete
conexao: Incomplete
cursor: Incomplete

def criar_tabela(conexao, cursor) -> None: ...
def inserir_cliente(conexao, cursor, nome, email) -> None: ...
def atualizar_cliente(conexao, cursor, cliente_id, nome, email) -> None: ...
def excluir_cliente(conexao, cursor, cliente_id) -> None: ...
def inserir_clientes_em_lote(conexao, cursor, clientes) -> None: ...
def recuperar_cliente(conexao, cursor, cliente_id): ...
def recuperar_clientes(conexao, cursor): ...
