from _typeshed import Incomplete
from dio_blog.schemas.post import PostRequest as PostRequest, PostUpdateRequest as PostUpdateRequest
from dio_blog.security import login_required as login_required
from dio_blog.service.post import PostService as PostService
from dio_blog.view.post import PostResponse as PostResponse

service: Incomplete
router: Incomplete

async def read_posts(published: bool = False, limit: int = 10, skip: int = 0): ...
async def read_post(id: int): ...
async def create_post(post: PostRequest): ...
async def update_post(id: int, post: PostUpdateRequest): ...
async def delete_post(id: int): ...
